### ISSUE TITLE
Práctica 5

### ISSUE THREAD

**Issue by Luisangelriverosbautista** [SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-30-equpio-lor-xd#1]
[REPORTE DE PRACTICA 5.pdf](https://github.com/user-attachments/files/17156321/REPORTE.DE.PRACTICA.5.pdf)

**Comment by Aylin67** [comment]
19

**Comment by josealfredo79** [comment]
@Luisangelriverosbautista Felicidades bien hecho y revisado...
